{ lib, stdenv, gnu-efi, gcc, binutils,
  uartBase ? 1016, # 0x3F8 = COM1
  baudRate ? 115200,
  uartClock ? 1843200,
  dataBits ? 8,
  parity ? "none",
  stopBits ? 1,
  loaderPath ? "\\EFI\\systemd\\systemd-bootx64.efi",
  bootTitle ? "Serial console (systemd-boot)",
}:

let
  # Validate parity
  parityNum = {
    none = 0;
    odd = 1;
    even = 2;
  }.${parity} or (throw "serial-boot-wrapper: parity must be \"none\", \"odd\" or \"even\"");

  # Validate data bits (16550 supports 5..8)
  dataBitsNum = toString dataBits;
  dataBitsCheck = lib.throwIf (dataBits < 5 || dataBits > 8)
    "serial-boot-wrapper: dataBits must be 5..8" true;

  # Validate stop bits
  stopBitsCheck = lib.throwIf (stopBits != 1 && stopBits != 2)
    "serial-boot-wrapper: stopBits must be 1 or 2" true;

  # Compute the UART divisor here so misconfiguration fails at evaluation
  # time, not deep inside the firmware.
  divisorCheck = lib.throwIf ((uartClock / (16 * baudRate)) * (16 * baudRate) != uartClock)
    "serial-boot-wrapper: uartClock (${toString uartClock}) must be divisible by 16 * baudRate (${toString (16 * baudRate)})" true;
  divisor = uartClock / (16 * baudRate);

  # Escape a CHAR16 C string literal for the config header
  escWide = s: "L\"${lib.replaceStrings [ "\\" ] [ "\\\\" ] s}\"";

  # Generate the config header as a plain list of lines so Nix's
  # indentation stripping cannot interfere.
  cfgLine = l: l + "\n";
  configH = lib.concatStrings [
    "/* Auto-generated by nix/serial-boot.nix - DO NOT EDIT */\n"
    "#ifndef SERIAL_BOOT_CONFIG_H\n"
    "#define SERIAL_BOOT_CONFIG_H\n"
    "\n"
    "#define CONFIG_UART_BASE       0x${lib.toHexString uartBase}\n"
    "#define CONFIG_UART_BAUD       ${toString baudRate}\n"
    "#define CONFIG_UART_CLOCK      ${toString uartClock}\n"
    "#define CONFIG_UART_DATA_BITS  ${dataBitsNum}\n"
    "#define CONFIG_UART_PARITY     ${toString parityNum}\n"
    "#define CONFIG_UART_STOP_BITS  ${toString stopBits}\n"
    "#define CONFIG_LOADER_PATH     ${escWide loaderPath}\n"
    "#define CONFIG_BOOT_TITLE      ${escWide bootTitle}\n"
    "\n"
    "#endif /* SERIAL_BOOT_CONFIG_H */\n"
  ];

  # Show the actual line settings in the derivation name/metadata
  parityLabel = parity;

  # Combine all validation results; forced when the drv attribute set is
  # built (i.e. on any use of the package).
  validation = dataBitsCheck && stopBitsCheck && divisorCheck && (parityNum >= 0);
in
stdenv.mkDerivation {
  pname = "serial-boot-wrapper";
  version = "0.1.0";

  src = ./..;

  nativeBuildInputs = [ gnu-efi gcc binutils ];

  # Disable all hardening: PIC changes codegen for the freestanding EFI
  # build and stack-protector/fortify pull in glibc symbols.
  hardeningDisable = [ "all" ];

  # Expose configuration for traceability (nix show-derivation / why-depends)
  passthru = {
    inherit uartBase baudRate uartClock dataBits parity stopBits loaderPath bootTitle;
    configValidated = validation;
  };

  passAsFile = [ "configH" ];
  inherit configH;

  configurePhase = ''
    runHook preConfigure
    mkdir -p config
    cp "$configHPath" config/config.h
    runHook postConfigure
  '';

  buildPhase = ''
    # Clean any stale artifacts that accidentally got into the source copy,
    # so make cannot consider the build up to date with an old .efi/.
    make -C src clean
    # Build the EFI application
    make -C src \
      CC="${stdenv.cc.targetPrefix}gcc" \
      LD="${stdenv.cc.targetPrefix}ld" \
      OBJCOPY="${binutils}/bin/objcopy" \
      EFIINC="${gnu-efi}/include/efi" \
      EFILIB="${gnu-efi}/lib" \
      ARCH=x86_64 \
      CONFIGDIR="$PWD/config"
  '';

  installPhase = ''
    mkdir -p $out/EFI/serial-boot
    cp src/serial-bootx64.efi $out/EFI/serial-boot/
  '';

  meta = with lib; {
    description = "EFI wrapper to mirror systemd-boot output to serial console (${toString baudRate} baud, ${parityLabel} parity)";
    license = licenses.mit;
    platforms = [ "x86_64-linux" ];
    maintainers = [];
  };
}
