/**
 * serial-boot.c - EFI wrapper to mirror systemd-boot output to a serial console
 *
 * This application initializes a 16550-compatible UART (parameters are set
 * at build time through a Nix-generated config.h), loads and starts
 * systemd-boot, and proxies all console output to both the screen and the
 * serial port.
 *
 * Why replacing SystemTable->ConOut is sufficient for systemd-boot 260.x:
 * systemd-boot reads ST->ConOut on every call (verified in systemd v260.2
 * sources: src/boot/boot.c, console.c, util.c, efi-log.c, graphics.c all
 * dereference ST->ConOut each time; the DEFINE_EFI_MAIN_FUNCTION macro in
 * src/boot/util.h only caches ST/BS/RT, never ConOut). There is no
 * GOP-backed graphics console in the text menu path, so a proxy installed
 * in the system table sees every OutputString()/ClearScreen()/
 * SetCursorPosition()/... the bootloader performs.
 */

#include <efi.h>
#include <efilib.h>
#include <efidef.h>
#include <efidevp.h>
#include <efiprot.h>

/* Optional build-time configuration generated by nix/serial-boot.nix.
 * The Makefile adds -I$(CONFIGDIR) when a Nix build is used; standalone
 * Make builds fall back to the defaults below. */
#ifdef CONFIGDIR_PRESENT
#include "config.h"
#endif

/* Build-time configuration (see nix/serial-boot.nix). Every value can be
 * overridden from the Nix expression; these fallbacks reproduce the classic
 * PC COM1 setup. */
#ifndef CONFIG_UART_BASE
#define CONFIG_UART_BASE 0x3F8
#endif
#ifndef CONFIG_UART_BAUD
#define CONFIG_UART_BAUD 115200
#endif
#ifndef CONFIG_UART_CLOCK
#define CONFIG_UART_CLOCK 1843200 /* standard 1.8432 MHz UART clock */
#endif
#ifndef CONFIG_UART_DATA_BITS
#define CONFIG_UART_DATA_BITS 8
#endif
#ifndef CONFIG_UART_PARITY
#define CONFIG_UART_PARITY 0 /* 0 = none, 1 = odd, 2 = even */
#endif
#ifndef CONFIG_UART_STOP_BITS
#define CONFIG_UART_STOP_BITS 1
#endif
#ifndef CONFIG_LOADER_PATH
#define CONFIG_LOADER_PATH L"\\EFI\\systemd\\systemd-bootx64.efi"
#endif
#ifndef CONFIG_BOOT_TITLE
#define CONFIG_BOOT_TITLE L"Serial console (systemd-boot)"
#endif

/* UART registers relative to the base port */
#define UART_REG_DATA    (CONFIG_UART_BASE + 0) /* Data register (RBR/THR) */
#define UART_REG_IER     (CONFIG_UART_BASE + 1) /* Interrupt Enable Register */
#define UART_REG_FCR     (CONFIG_UART_BASE + 2) /* FIFO Control Register */
#define UART_REG_LCR     (CONFIG_UART_BASE + 3) /* Line Control Register */
#define UART_REG_MCR     (CONFIG_UART_BASE + 4) /* Modem Control Register */
#define UART_REG_LSR     (CONFIG_UART_BASE + 5) /* Line Status Register */

/* Computed divisor: 16 * baud must divide the UART input clock */
#define UART_DIVISOR (CONFIG_UART_CLOCK / (16 * CONFIG_UART_BAUD))
#if (CONFIG_UART_CLOCK % (16 * CONFIG_UART_BAUD)) != 0
#error "CONFIG_UART_CLOCK is not divisible by 16 * CONFIG_UART_BAUD"
#endif

/* Line Control Register bits */
#define LCR_DLAB         0x80 /* Divisor Latch Access Bit */
#define LCR_STOP2        0x04 /* 2 stop bits instead of 1 */
#define LCR_PARITY_EN    0x08 /* enable parity */
#define LCR_PARITY_EVEN  0x10 /* even parity (else odd) */
#define LCR_DATA_BITS(n) ((n) - 5) /* encoded data bits, 5..8 */

/* Line Status Register bits */
#define LSR_THRE         0x20 /* Transmitter Holding Register Empty */

/* FIFO Control Register bits */
#define FCR_ENABLE_FIFO  0x01 /* Enable FIFO */
#define FCR_CLEAR_RX     0x02 /* Clear receiver FIFO */
#define FCR_CLEAR_TX     0x04 /* Clear transmitter FIFO */

/* Modem Control Register bits */
#define MCR_DTR          0x01 /* Data Terminal Ready */
#define MCR_RTS          0x02 /* Request To Send */

/* Safety timeout so a dead/broken UART can never hang the boot process.
 * Bounded polling; generous on purpose. */
#define UART_THRE_MAX_POLLS 100000

/* Numeric parity values written by the Nix config generator */
#define UART_PARITY_NONE 0
#define UART_PARITY_ODD  1
#define UART_PARITY_EVEN 2

/* Build the LCR value (without DLAB) from the configured line format */
static UINT8 uart_lcr_value(void)
{
    UINT8 lcr = LCR_DATA_BITS(CONFIG_UART_DATA_BITS);

#if CONFIG_UART_STOP_BITS == 2
    lcr |= LCR_STOP2;
#endif

#if CONFIG_UART_PARITY == UART_PARITY_EVEN
    lcr |= LCR_PARITY_EN | LCR_PARITY_EVEN;
#elif CONFIG_UART_PARITY == UART_PARITY_ODD
    lcr |= LCR_PARITY_EN;
#elif CONFIG_UART_PARITY != UART_PARITY_NONE
#error "CONFIG_UART_PARITY must be 0 (none), 1 (odd) or 2 (even)"
#endif

    return lcr;
}

/* Global state */
static EFI_SIMPLE_TEXT_OUT_PROTOCOL *OriginalConOut = NULL;
static EFI_SIMPLE_TEXT_OUT_PROTOCOL ProxyConOut;
/* The Mode structure shared by the proxy. systemd-boot reads Mode->Mode,
 * Mode->MaxMode, Mode->Attribute etc. directly; we keep a pointer to the
 * original console's mode data so state tracking stays in sync with the
 * firmware console that actually processes the operations. */
static SIMPLE_TEXT_OUTPUT_MODE *OriginalMode = NULL;

/* ============================================================================
 * UART Functions
 * ============================================================================ */

/**
 * Write a byte to an I/O port
 */
static inline void outb(UINT16 port, UINT8 value)
{
    __asm__ __volatile__ ("outb %0, %1" : : "a"(value), "Nd"(port));
}

/**
 * Read a byte from an I/O port
 */
static inline UINT8 inb(UINT16 port)
{
    UINT8 value;
    __asm__ __volatile__ ("inb %1, %0" : "=a"(value) : "Nd"(port));
    return value;
}

/**
 * Wait for the Transmitter Holding Register to be empty.
 * Bounded so that hardware failure cannot hang the boot.
 */
static void uart_wait_thre(void)
{
    UINTN polls = UART_THRE_MAX_POLLS;
    while (!(inb(UART_REG_LSR) & LSR_THRE)) {
        if (--polls == 0)
            return;
    }
}

/**
 * Initialize the 16550 UART with the configured line parameters
 */
static void uart_init(void)
{
    /* Disable interrupts */
    outb(UART_REG_IER, 0x00);

    /* Set DLAB to access divisor latch */
    outb(UART_REG_LCR, LCR_DLAB);

    /* Set divisor for the configured baud rate */
    outb(UART_REG_DATA, (UINT8)(UART_DIVISOR & 0xFF));       /* low byte */
    outb(UART_REG_IER, (UINT8)((UART_DIVISOR >> 8) & 0xFF)); /* high byte */

    /* Set line format and clear DLAB */
    outb(UART_REG_LCR, uart_lcr_value());

    /* Enable and clear FIFOs */
    outb(UART_REG_FCR, FCR_ENABLE_FIFO | FCR_CLEAR_RX | FCR_CLEAR_TX);

    /* Set DTR and RTS */
    outb(UART_REG_MCR, MCR_DTR | MCR_RTS);
}

/**
 * Send a single character to the UART
 */
static void uart_putc(char c)
{
    uart_wait_thre();
    outb(UART_REG_DATA, (UINT8)c);
}

/**
 * Send a null-terminated string to the UART
 */
static void uart_puts(const char *str)
{
    while (*str) {
        uart_putc(*str++);
    }
}

/**
 * Send a UTF-16 string to the UART, converting to ASCII
 * Handles CR/LF conversion for serial terminals
 */
static void uart_puts_utf16(const CHAR16 *str)
{
    while (*str) {
        CHAR16 c = *str++;

        /* Convert CR/LF for serial terminal */
        if (c == L'\r') {
            uart_putc('\r');
            uart_putc('\n');
        } else if (c == L'\n') {
            uart_putc('\r');
            uart_putc('\n');
        } else if (c < 0x80) {
            /* ASCII range - send directly */
            uart_putc((char)c);
        } else {
            /* Non-ASCII - send placeholder */
            uart_putc('?');
        }
    }
}

/* ============================================================================
 * Small ANSI helpers for the serial side
 * ============================================================================ */

/**
 * Decimal escape sequence helper: writes <n><suffix>
 */
static void uart_num_suffix(UINTN n, char suffix)
{
    char tmp[12];
    int i = 0;

    if (n == 0) {
        uart_putc('0');
    } else {
        while (n > 0 && i < (int)sizeof(tmp)) {
            tmp[i++] = '0' + (n % 10);
            n /= 10;
        }
        while (i > 0)
            uart_putc(tmp[--i]);
    }
    uart_putc(suffix);
}

/* ============================================================================
 * EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL Proxy
 * ============================================================================ */

/**
 * Proxy OutputString - send to both serial and original console
 */
static EFI_STATUS EFIAPI ProxyOutputString(
    IN EFI_SIMPLE_TEXT_OUT_PROTOCOL *This,
    IN CHAR16 *String
)
{
    EFI_STATUS status;

    (void)This;

    /* Send to serial first (before potential screen output) */
    uart_puts_utf16(String);

    /* Send to original console */
    status = OriginalConOut->OutputString(OriginalConOut, String);

    return status;
}

/**
 * Proxy TestString - test on original console
 */
static EFI_STATUS EFIAPI ProxyTestString(
    IN EFI_SIMPLE_TEXT_OUT_PROTOCOL *This,
    IN CHAR16 *String
)
{
    (void)This;
    return OriginalConOut->TestString(OriginalConOut, String);
}

/**
 * Proxy Reset - reset original console; clear the serial line too
 */
static EFI_STATUS EFIAPI ProxyReset(
    IN EFI_SIMPLE_TEXT_OUT_PROTOCOL *This,
    IN BOOLEAN ExtendedVerification
)
{
    (void)This;
    uart_puts("\033[2J\033[H");
    return OriginalConOut->Reset(OriginalConOut, ExtendedVerification);
}

/**
 * Proxy QueryMode - query on original console
 */
static EFI_STATUS EFIAPI ProxyQueryMode(
    IN EFI_SIMPLE_TEXT_OUT_PROTOCOL *This,
    IN UINTN ModeNumber,
    OUT UINTN *Columns,
    OUT UINTN *Rows
)
{
    (void)This;
    return OriginalConOut->QueryMode(OriginalConOut, ModeNumber, Columns, Rows);
}

/**
 * Proxy SetMode - set on original console
 */
static EFI_STATUS EFIAPI ProxySetMode(
    IN EFI_SIMPLE_TEXT_OUT_PROTOCOL *This,
    IN UINTN ModeNumber
)
{
    EFI_STATUS status;

    (void)This;
    status = OriginalConOut->SetMode(OriginalConOut, ModeNumber);
    if (!EFI_ERROR(status)) {
        /* New mode implies a cleared screen on the video console */
        uart_puts("\033[2J\033[H");
    }
    return status;
}

/**
 * Proxy SetAttribute - set on original console; ignore attribute on serial
 * (plain serial terminals have no colors; stripping is intentional)
 */
static EFI_STATUS EFIAPI ProxySetAttribute(
    IN EFI_SIMPLE_TEXT_OUT_PROTOCOL *This,
    IN UINTN Attribute
)
{
    (void)This;
    return OriginalConOut->SetAttribute(OriginalConOut, Attribute);
}

/**
 * Proxy ClearScreen - clear on original console and send ANSI to serial
 */
static EFI_STATUS EFIAPI ProxyClearScreen(
    IN EFI_SIMPLE_TEXT_OUT_PROTOCOL *This
)
{
    (void)This;
    /* Send ANSI clear screen sequence to serial */
    uart_puts("\033[2J\033[H");

    return OriginalConOut->ClearScreen(OriginalConOut);
}

/**
 * Proxy SetCursorPosition - set on original console
 */
static EFI_STATUS EFIAPI ProxySetCursorPosition(
    IN EFI_SIMPLE_TEXT_OUT_PROTOCOL *This,
    IN UINTN Column,
    IN UINTN Row
)
{
    EFI_STATUS status;

    (void)This;
    /* Send ANSI cursor position to serial (1-based) */
    uart_puts("\033[");
    uart_num_suffix(Row + 1, ';');
    uart_num_suffix(Column + 1, 'H');

    status = OriginalConOut->SetCursorPosition(OriginalConOut, Column, Row);
    return status;
}

/**
 * Proxy EnableCursor - enable/disable on original console
 */
static EFI_STATUS EFIAPI ProxyEnableCursor(
    IN EFI_SIMPLE_TEXT_OUT_PROTOCOL *This,
    IN BOOLEAN Visible
)
{
    (void)This;
    /* Send ANSI cursor visibility to serial */
    if (Visible) {
        uart_puts("\033[?25h");
    } else {
        uart_puts("\033[?25l");
    }

    return OriginalConOut->EnableCursor(OriginalConOut, Visible);
}

/**
 * Initialize the proxy ConOut protocol
 */
static void init_proxy_conout(void)
{
    /* Copy original protocol structure */
    CopyMem(&ProxyConOut, OriginalConOut, sizeof(EFI_SIMPLE_TEXT_OUT_PROTOCOL));

    /* Replace function pointers with our proxies */
    ProxyConOut.Reset = ProxyReset;
    ProxyConOut.OutputString = ProxyOutputString;
    ProxyConOut.TestString = ProxyTestString;
    ProxyConOut.QueryMode = ProxyQueryMode;
    ProxyConOut.SetMode = ProxySetMode;
    ProxyConOut.SetAttribute = ProxySetAttribute;
    ProxyConOut.ClearScreen = ProxyClearScreen;
    ProxyConOut.SetCursorPosition = ProxySetCursorPosition;
    ProxyConOut.EnableCursor = ProxyEnableCursor;

    /* Share the original Mode structure so console state (cursor position,
     * attribute, current mode) is owned by the firmware console that really
     * executes the operations. */
    ProxyConOut.Mode = OriginalMode;
}

/* ============================================================================
 * File Loading Helpers
 * ============================================================================ */

/**
 * Open the volume that contains the running wrapper (via LoadedImage).
 * This works for any device the firmware can read (ESP or otherwise);
 * no disk or partition UUID is hardcoded.
 */
static EFI_STATUS open_self_volume(EFI_HANDLE image_handle,
                                   EFI_FILE_IO_INTERFACE **volume)
{
    EFI_STATUS status;
    EFI_LOADED_IMAGE_PROTOCOL *loaded_image = NULL;

    status = gBS->HandleProtocol(
        image_handle,
        &gEfiLoadedImageProtocolGuid,
        (VOID **)&loaded_image
    );
    if (EFI_ERROR(status)) {
        uart_puts("[serial-boot] ERROR: Failed to get loaded image protocol\n");
        return status;
    }

    if (loaded_image->DeviceHandle == NULL) {
        uart_puts("[serial-boot] ERROR: NULL device handle\n");
        return EFI_UNSUPPORTED;
    }

    status = gBS->HandleProtocol(
        loaded_image->DeviceHandle,
        &gEfiSimpleFileSystemProtocolGuid,
        (VOID **)volume
    );
    if (EFI_ERROR(status)) {
        uart_puts("[serial-boot] ERROR: No SimpleFileSystem on our device\n");
        return status;
    }

    return EFI_SUCCESS;
}

/**
 * Read a full file from a volume. Caller frees *buffer.
 */
static EFI_STATUS read_file(EFI_FILE_HANDLE root, CHAR16 *path,
                            VOID **buffer, UINTN *buffer_size)
{
    EFI_STATUS status;
    EFI_FILE_HANDLE file = NULL;
    UINTN info_size = 0;
    EFI_FILE_INFO *info = NULL;
    VOID *data = NULL;

    status = root->Open(root, &file, path, EFI_FILE_MODE_READ, 0);
    if (EFI_ERROR(status)) {
        uart_puts("[serial-boot] ERROR: cannot open loader binary\n");
        return status;
    }

    /* First GetInfo call with size 0 must return EFI_BUFFER_TOO_SMALL and
     * set info_size to the required size. */
    status = file->GetInfo(file, &GenericFileInfo, &info_size, NULL);
    if (status != EFI_BUFFER_TOO_SMALL || info_size == 0) {
        uart_puts("[serial-boot] ERROR: GetInfo(size probe) failed\n");
        file->Close(file);
        return EFI_ABORTED;
    }

    info = AllocatePool(info_size);
    if (info == NULL) {
        uart_puts("[serial-boot] ERROR: cannot allocate file info\n");
        file->Close(file);
        return EFI_OUT_OF_RESOURCES;
    }

    status = file->GetInfo(file, &GenericFileInfo, &info_size, info);
    if (EFI_ERROR(status)) {
        uart_puts("[serial-boot] ERROR: GetInfo failed\n");
        FreePool(info);
        file->Close(file);
        return status;
    }

    if (info->FileSize == 0) {
        uart_puts("[serial-boot] ERROR: loader file is empty\n");
        FreePool(info);
        file->Close(file);
        return EFI_ABORTED;
    }

    *buffer_size = (UINTN)info->FileSize;
    FreePool(info);
    info = NULL;

    data = AllocatePool(*buffer_size);
    if (data == NULL) {
        uart_puts("[serial-boot] ERROR: cannot allocate file buffer\n");
        file->Close(file);
        return EFI_OUT_OF_RESOURCES;
    }

    status = file->Read(file, buffer_size, data);
    if (EFI_ERROR(status)) {
        uart_puts("[serial-boot] ERROR: Read failed\n");
        FreePool(data);
        file->Close(file);
        return status;
    }

    file->Close(file);
    *buffer = data;
    return EFI_SUCCESS;
}

/**
 * Print an unsigned number in decimal over the UART
 */
static void uart_put_uint(UINTN value)
{
    char tmp[24];
    int i = 0;

    if (value == 0) {
        uart_putc('0');
        return;
    }
    while (value > 0) {
        tmp[i++] = '0' + (value % 10);
        value /= 10;
    }
    while (i > 0)
        uart_putc(tmp[--i]);
}

/* ============================================================================
 * EFI Application Entry Point
 * ============================================================================ */

/**
 * Find and load the configured loader binary from the same volume
 * as this wrapper
 */
static EFI_STATUS load_systemd_boot(EFI_HANDLE image_handle)
{
    EFI_STATUS status;
    EFI_FILE_IO_INTERFACE *volume = NULL;
    EFI_FILE_HANDLE root = NULL;
    VOID *buffer = NULL;
    UINTN size = 0;
    EFI_HANDLE new_image = NULL;

    /* Open the volume this wrapper was started from (no hardcoded UUIDs) */
    status = open_self_volume(image_handle, &volume);
    if (EFI_ERROR(status))
        return status;

    status = volume->OpenVolume(volume, &root);
    if (EFI_ERROR(status)) {
        uart_puts("[serial-boot] ERROR: OpenVolume failed\n");
        return status;
    }

    status = read_file(root, CONFIG_LOADER_PATH, &buffer, &size);
    root->Close(root);
    if (EFI_ERROR(status))
        return status;

    uart_puts("[serial-boot] loaded loader image: ");
    uart_put_uint(size);
    uart_puts(" bytes\n");

    /* Load the image from the buffer. We pass no device path; the firmware
     * records our own image as the parent. */
    status = gBS->LoadImage(
        FALSE,          /* BootPolicy: not booting the default loader */
        image_handle,
        NULL,           /* no device path, loading from memory buffer */
        buffer,
        size,
        &new_image
    );

    /* The firmware has copied the image into its own memory by now */
    FreePool(buffer);
    buffer = NULL;

    if (EFI_ERROR(status)) {
        uart_puts("[serial-boot] ERROR: LoadImage failed\n");
        return status;
    }

    /* Install our proxy ConOut before starting the new image */
    init_proxy_conout();

    /* Replace SystemTable->ConOut with our proxy */
    gST->ConOut = &ProxyConOut;

    uart_puts("[serial-boot] starting loader...\n");

    /* Start the image */
    status = gBS->StartImage(new_image, NULL, NULL);

    /* If we get here, the loader returned (e.g. menu quit or boot failed) */
    uart_puts("[serial-boot] loader returned\n");

    /* Restore original ConOut */
    gST->ConOut = OriginalConOut;

    return status;
}

/**
 * EFI application entry point
 */
EFI_STATUS EFIAPI efi_main(EFI_HANDLE image_handle, EFI_SYSTEM_TABLE *system_table)
{
    EFI_STATUS status;

    /* Initialize the UEFI library */
    InitializeLib(image_handle, system_table);

    /* Initialize UART */
    uart_init();
    uart_puts("\n[serial-boot] wrapper started\n");
    uart_puts("[serial-boot] UART initialized at ");
    uart_put_uint(CONFIG_UART_BASE);
    uart_puts(" (");
    uart_put_uint(CONFIG_UART_BAUD);
    uart_puts(" baud)\n");

    /* Save original ConOut and its Mode structure */
    OriginalConOut = system_table->ConOut;
    if (OriginalConOut == NULL) {
        uart_puts("[serial-boot] ERROR: no ConOut in system table\n");
        return EFI_UNSUPPORTED;
    }
    OriginalMode = OriginalConOut->Mode;

    /* Load and start the loader */
    uart_puts("[serial-boot] loading loader...\n");
    status = load_systemd_boot(image_handle);

    if (EFI_ERROR(status)) {
        uart_puts("[serial-boot] ERROR: failed to load/start loader\n");
        /* Restore original ConOut on error */
        gST->ConOut = OriginalConOut;
    }

    return status;
}
